import java.io.*;
import java.util.Scanner;

public class exceptionHandling  {
   public static void main(String[] args) {
       

	   Scanner s = new Scanner(System.in);
       
	   int i,j,temp,m,n;
	   int flag=1;
       
      
	   System.out.println("Enter The Size Of Array 1: ");
	   n = s.nextInt();
		
       System.out.println("Enter The Size Of Array 2: ");
       m = s.nextInt();
	   
	   int[] a = new int[n];
	   int[] b = new int[m];
	   
	   System.out.println("\nEnter The Elements Of Array 1: \n");
       for(i=0;i<n;++i)
	   {
		   a[i] = s.nextInt();
		   
	   }
           
       System.out.println("\nEnter The Elements Of Array 2: \n");
       for(i=0;i<m;++i)
	   {
		   b[i] = s.nextInt();
		   
	   }
           
	 
		
		
		
		try
	   {
		
		if(m!=n)
		{
		
				throw new ArrayIndexOutOfBoundsException();
				
	    }
        
		for(i=0;i<n;i++)
		{
				
				temp=a[i]/b[i];
				a[i]=temp;
				
			
			
		}
	
		
		
	   }
	   
	   catch(ArrayIndexOutOfBoundsException e)
	   {
		
		   System.out.println("ARRAY SIZE SHOULD BE SAME");
		   System.out.println("ARRAY SIZE ARE "+m+" and "+n);
		   flag=0;
		   
	   }
		
	   
		
		
	   
	   
	   
	   
	   
	   catch(ArithmeticException e)
	   {
		  
		   System.out.println("DIVISION BY ZERO");
		   flag=0;
	   }
	    
	   
	   finally
	   {
		  
			//printing
			if(flag!=0)
			{
			   System.out.println("Array value after division :");
			   for(i=0;i<m;i++)
			   {
				 System.out.print(a[i]+" ");
			   }
		   }
			System.out.println("\nOperation completed");
	   }
